### ISSUE TITLE
The 1.20.5 release doesn't work with 1.20.6

### ISSUE THREAD

**Issue by Abbanon** [vladmarica/better-ping-display-fabric#39]
![Screenshot_1](https://github.com/vladmarica/better-ping-display-fabric/assets/37251822/2d198af1-9514-4324-8510-1fe46ab6f545)
[crash log.txt](https://github.com/vladmarica/better-ping-display-fabric/files/15281269/crash.log.txt)

**Comment by ItsRodrigoAl** [comment]
bump

**Comment by matixandr** [comment]
bump

**Comment by MusclePr** [comment]
If there are no major changes such as from 1.20.5 to 1.20.6 due to temporary bug fixes,
it may be possible to create a jar just by changing the version.

(Requires [jdk 17](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html) and [git](https://gitforwindows.org/).)

1. First, get the latest source code from the repository.
```bash
$ git clone https://github.com/vladmarica/better-ping-display-fabric.git
$ cd better-ping-display-fabric
```
2. Let's change gradle.properties as below.
The [fabric develop](https://fabricmc.net/develop/) will be helpful.
```diff
diff --git a/gradle.properties b/gradle.properties
index b931e88..c5d601a 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -3,14 +3,14 @@ org.gradle.jvmargs=-Xmx1G

 # Fabric Properties
        # check these on https://fabricmc.net/use
-       minecraft_version=1.20.5
-       yarn_mappings=1.20.5+build.1
+       minecraft_version=1.20.6
+       yarn_mappings=1.20.6+build.2
        loader_version=0.15.11

 # Mod Properties
-       mod_version = 1.1.1
+       mod_version = 1.1.2
        maven_group = com.vladmarica
        archives_base_name = BetterPingDisplay-Fabric

 # Dependencies
-       fabric_version=0.97.8+1.20.5
+       fabric_version=0.99.0+1.20.6
```
3. build it
```bash
$ ./gradlew --no-daemon build
```
4. We get from `build/libs/BetterPingDisplay-Fabric-<mod_version>.jar`.

It's not official, but I'll attached.
[BetterPingDisplay-Fabric-1.1.2-not-official.jar.zip](https://github.com/vladmarica/better-ping-display-fabric/files/15396940/BetterPingDisplay-Fabric-1.1.2-not-official.jar.zip)

**Comment by vladmarica** [comment]
Modrinth: https://modrinth.com/mod/better-ping-display-fabric/version/1.20.6-1.1.1
CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/better-ping-display-fabric/files/5372653
